### PR TITLE
Downgrade Node.js to fix builds on Travis CI

### PR DESCRIPTION
**Pull request by meisenzahl**

### CODE REVIEW

**Comment by dar5hak** [comment]
Eh, I was planning to do this but I slacked off! :sweat_smile: 

Thank you @meisenzahl!

However now it's failing for a different reason. C'est la vie. :sweat:

**Comment by meisenzahl** [comment]
Apparently the error is due to a missing icon:

`meson.build:48:4: ERROR:  File data/icons/256/com.github.elfenware.badger.svg does not exist.`

https://travis-ci.org/elfenware/badger/builds/609371978#L3290

**Comment by dar5hak** [comment]
Crap, how could I miss that?

**Comment by meisenzahl** [comment]
Sometimes a second pair of eyes is helpful 😉️

**Pull request merged**
