### PR TITLE
update_ukrainian_translation

### PR DESCRIPTION
**Pull request by IhorHordiichuk**

### CODE REVIEW

**Comment by dar5hak** [comment]
Thanks a lot @IhorHordiichuk!

I also see I might have misspelt your username in a few files, sorry. I will fix that.

**Comment by dar5hak** [comment]
[Done](https://github.com/elfenware/badger/pull/62/commits/009846880165e3756d1aaf6a55525bef1ffbd515).

**Comment by IhorHordiichuk** [comment]
> Thanks a lot @IhorHordiichuk!
> 
> I also see I might have misspelt your username in a few files, sorry. I will fix that.

Sorry. It's not your fault, I recently changed my username a bit, due to the problems of "normal" transliteration of my name.

**Comment by dar5hak** [comment]
Ah, okay. No problem, all updated now!

**Pull request merged**
