### PR TITLE
Add French translations + Adjustments

### PR DESCRIPTION
**Pull request by NathanBnm**
Hey I have updated translation strings and added French translations :smile:

# Changelog

- Updated `com.github.elfenware.badger.pot`
- Created  `fr.po`
- Added `fr` to `LINGUAS`

- Added new release to `appdata.xml`
*Note: You may have to change the release date*

**This PR is ready for review**

### CODE REVIEW

**Comment by dar5hak** [comment]
Hey @NathanBnm, merci beaucoup for the translations! That was fast! :smiley: 

Looks like Houston CI has a problem with appstream URLs in the description. AppCenter doesn't render their markup anyway, so I'll remove them from both English and French descriptions.

Thanks again!

**Comment by NathanBnm** [comment]
I just saw the app on the main page of the AppCenter and I found it cute XD And very usefull, so I just said to myself "Let's translate this too!"

Yes that was the first time I saw links like that, AppCenter doesn't car about these links. I added them too just because they were there 😄

**Comment by dar5hak** [comment]
Yup, and I see you actively translating loads of elementary OS apps to French. Keep up the great work! :raised_hands:

**Comment by NathanBnm** [comment]
Thanks

**Pull request merged**
