### PR TITLE
Add new reminder: Posture

### PR DESCRIPTION
**Pull request by dar5hak**

### CODE REVIEW

**Comment by dar5hak** [comment]
Okay, why the heck would `npm i -g @elementaryos/houston` fail?

**Comment by dar5hak** [comment]
@NathanBnm @welaq @siigdev @Vistaus @libreajans Folks, if you have some time, could you add a translation for this new reminder? Just three new strings.

If you do, you can make a pull request to this branch (`posture`). Thank you! :relaxed:

**Comment by siigdev** [comment]
Sure! 
I'll look at it one of the next days if I have time.

**Comment by libreajans** [comment]
Could you update the pot file?

**Comment by dar5hak** [comment]
@libreajans Ah, my bad. Gimme a few minutes.

**Comment by dar5hak** [comment]
Okay that's more than three strings, but you don't really need to do the release notes. 🤔️

**Comment by Vistaus** [comment]
> Okay that's more than three strings, but you don't really need to do the release notes.

I did them anyway :D https://github.com/elfenware/badger/pull/36

**Comment by NathanBnm** [comment]
@dar5hak Sure I'll dot that soon when I have time!

**Comment by dar5hak** [comment]
Thank you so much, folks!

**Comment by welaq** [comment]
Hi, since elementary OS started to promote some strange communities (see their logo in github) I have decided to stop contributing to the project.
And since this app is built for elementary OS I won't be making any pull requests. Sorry about that.

**Comment by NathanBnm** [comment]
>Hi, since elementary OS started to >promote **some strange** communities (see >their logo in github) I have decided to stop >contributing to the project.
>
Lol

**Comment by dar5hak** [comment]
@welaq Our opinions differ here. Thank you for your contributions so far.

**Comment by dar5hak** [comment]
Thank you, @NathanBnm

**Pull request merged**
