### PR TITLE
Add Badger to the notification center (#34)

### LINKED ISSUE #34: Notification control
When a notification pop out, I look away my screen, and when I come back, the notification is gone but not really : it's still in the notification center. As I can't turn off the notification center feature for all the "others" apps, it would be really handy if Badger was known by the system-wide notification system. I found out that adding `X-GNOME-UsesNotifications=true` in the `.desktop` file enable something like this, which is exactly what I needed. 
Screenshot from 2019-10-23 19-25-56
What are you thoughts ?

### PR DESCRIPTION
**Pull request by nathanaelhoun**
This closes #34.

### CODE REVIEW

**Comment by dar5hak** [comment]
@nathanaelhoun Thank you! The build is failing due to https://github.com/elementary/houston/issues/755, which is actually fixed and will be available in the next release of Houston. Once that's in place, I'll merge this.

**Comment by nathanaelhoun** [comment]
Nice ! Happy to see my first PR (even if it's a little one) accepted :wink:

**Comment by dar5hak** [comment]
@nathanaelhoun It might be a one-liner but it has a big positive impact. For me personally (and I'm sure for many others), it solves a frustrating problem with Badger. :smile:

**Comment by dar5hak** [comment]
Chuck it, I'll just merge it. It's not like this is gonna break anything (says my inner Anatoly Dyatlov).

**Pull request merged**
